### PR TITLE
Feature/improve delete and moving commands

### PR DESCRIPTION
**Pull request by lagartoverde**
Made the moving just switch the 2 affected articles, so text between articles is preserved.
Also now when deleting an article the numbers are recalculated

### CODE REVIEW

**Review by nvdk — CHANGES_REQUESTED** [review]
while overall it seems to be working ok, there's an issue when moving articles down. It isn't renumbering properly after that
See 
https://user-images.githubusercontent.com/878686/161225637-fff0e3ad-ba55-4fb4-846d-6fec5686b13b.mp4

**Comment by lagartoverde** [comment]
I have been trying for a while and can't reproduce, are you able to? If so are you getting any error on the console, this is weird

**Comment by lagartoverde** [comment]
Oh wait, I'm stupid this requires the editor in latest dev, arne has just merged a fix for that bug and I forgot that I have it npm linked

**Comment by abeforgit** [comment]
can this be merged and released soon? it's blocking an upgrade of the editor in GN

**Pull request merged**
