### PR TITLE
Feature / Widget redesign

### PR DESCRIPTION
**Pull request by benjay10**
This PR redesigns this plugin with the new "Insert" menu in mind.

To make sense of this, "Insert article" and "Insert decision title" are static buttons that are now displayed in the new insert menu (unless there already is a decision title in the document). Other buttons about articles are more context driven and are still in their original card.
afbeelding

No idea what the best approach is for this plugin, because it seems that half of it is semi-static and the other half is more context driven.

Also, package upgrades to new AppUniversum are included, which makes this PR https://github.com/lblod/ember-rdfa-editor-besluit-plugin/pull/12 redundant (?).

### CODE REVIEW

**Comment by benjay10** [comment]
Thanks to @Dietr, lay-out has been updated to a more concise plugin-card, like so:
afbeelding

**Comment by benjay10** [comment]
As per new instructions, always show all buttons, but disabled when it's functionality is irrelevant due to the current context of the editor. This will be done in the next commit(s).

**Comment by Asergey91** [comment]
adding articles below/above seem to trigger errors im on latest dev gn, editor, and this branch

**Review by Asergey91 — APPROVED** [review]
had a chat about the above comment, seems to be resolved

**Pull request merged**
